# Generated by Django 2.0.9 on 2018-11-12 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0026_fix_org_config_rapidpro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('language', models.CharField(choices=[('bs', 'Bosnian'), ('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('uk', 'Ukrainian'), ('uz', 'Uzbek'), ('my', 'Burmese'), ('id', 'Indonesian'), ('it', 'Italian'), ('ro', 'Romanian'), ('vi', 'Vietnamese'), ('sr', 'Serbian')], help_text='Choose the language', max_length=16)),
                ('policy_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('tos', 'Terms of Service'), ('cookie', 'Cookie Policy')], help_text='Choose the type of policy', max_length=16)),
                ('body', models.TextField(help_text='Enter the content of the policy (Markdown permitted)')),
                ('summary', models.TextField(blank=True, help_text='Summary of policy changes (Markdown permitted)', null=True)),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='policies_policy_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='policies_policy_modifications', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(help_text='The organization this item belongs to', on_delete=django.db.models.deletion.PROTECT, to='orgs.Org')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
