# Generated by Django 2.0.9 on 2018-11-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='summary',
        ),
    ]
