# Generated by Django 2.2.3 on 2019-07-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgeSegment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("min_age", models.IntegerField(null=True)),
                ("max_age", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GenderSegment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gender", models.CharField(max_length=1)),
            ],
        ),
    ]
