# Generated by Django 2.2.3 on 2019-08-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0026_fix_org_config_rapidpro"),
        ("polls", "0054_add_index_poll_question_ruleset_uuid"),
        ("locations", "0006_boundary_backend"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeSegment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("min_age", models.IntegerField(null=True)),
                ("max_age", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GenderSegment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gender", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="PollStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(null=True)),
                ("count", models.IntegerField(default=0, help_text="Number of items with this counter")),
                (
                    "age_segment",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="stats.AgeSegment"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="polls.PollResponseCategory"
                    ),
                ),
                (
                    "gender_segment",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="stats.GenderSegment"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="locations.Boundary"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="poll_stats", to="orgs.Org"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="polls.PollQuestion"
                    ),
                ),
            ],
        ),
    ]
