# Generated by Django 2.2.3 on 2019-08-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0026_fix_org_config_rapidpro"),
        ("locations", "0006_boundary_backend"),
        ("polls", "0053_poll_backend"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gender", models.CharField(max_length=1, null=True)),
                ("born", models.IntegerField(null=True)),
                ("date", models.DateTimeField(null=True)),
                ("count", models.IntegerField(default=0, help_text="Number of items with this counter")),
                (
                    "category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="polls.PollResponseCategory"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="locations.Boundary"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="poll_stats", to="orgs.Org"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="polls.PollQuestion"
                    ),
                ),
            ],
        )
    ]
