# Generated by Django 2.2.5 on 2019-10-11 14:11

from django.db import migrations

# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_GENDER = """
CREATE INDEX IF NOT EXISTS stats_contactactivity_org_id_date_gender
  on stats_contactactivity (org_id, date, gender);
"""

# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_STATE = """
CREATE INDEX IF NOT EXISTS stats_contactactivity_org_id_date_state
  on stats_contactactivity (org_id, date, state);
"""


# language=SQL
INDEX_SQL_POLLSTATS_ORG_DATE_GENDER = """
CREATE INDEX IF NOT EXISTS stats_pollstats_org_id_date_gender
  on stats_pollstats (org_id, date, gender_segment_id);
"""

# language=SQL
INDEX_SQL_POLLSTATS_ORG_DATE_AGE = """
CREATE INDEX IF NOT EXISTS stats_pollstats_org_id_date_age
  on stats_pollstats (org_id, date, age_segment_id);
"""


# language=SQL
INDEX_SQL_POLLSTATS_ORG_DATE_LOCATION = """
CREATE INDEX IF NOT EXISTS stats_pollstats_org_id_date_location
  on stats_pollstats (org_id, date, location_id);
"""


class Migration(migrations.Migration):
    dependencies = [("stats", "0003_contactactivity")]

    operations = [
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_GENDER),
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_STATE),
        migrations.RunSQL(INDEX_SQL_POLLSTATS_ORG_DATE_GENDER),
        migrations.RunSQL(INDEX_SQL_POLLSTATS_ORG_DATE_AGE),
        migrations.RunSQL(INDEX_SQL_POLLSTATS_ORG_DATE_LOCATION),
    ]
