# Generated by Django 2.2.5 on 2019-11-07 13:37

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0056_auto_20190926_1554"),
        ("orgs", "0026_fix_org_config_rapidpro"),
        ("stats", "0004_add_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollWordCloud",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("words", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ("org", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.Org")),
                (
                    "question",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="polls.PollQuestion"
                    ),
                ),
            ],
        )
    ]
