# Generated by Django 2.2.8 on 2019-12-10 16:01

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0006_populate_word_clouds"),
    ]

    operations = [InstallSQL("stats_0007")]
