# Generated by Django 2.2.8 on 2020-01-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_populate_word_clouds'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollstats',
            name='is_squashed',
            field=models.BooleanField(help_text='Whether this row was created by squashing', null=True),
        ),
    ]
