# Generated by Django 2.2.9 on 2020-01-28 08:52

from django.db import migrations

INDEX_SQL = """
CREATE INDEX IF NOT EXISTS stats_pollstats_org_question_category_age_gender_date_not_null
  on stats_pollstats (org_id, question_id, category_id, age_segment_id, gender_segment_id, location_id, date) WHERE date IS NOT NULL;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0007_pollstats_is_squashed"),
    ]

    operations = [migrations.RunSQL(INDEX_SQL)]
