# Generated by Django 2.2.20 on 2021-05-26 16:49

from django.db import migrations

INDEX_SQL = """
CREATE INDEX IF NOT EXISTS stats_pollstats_org_question on stats_pollstats (org_id, question_id) WHERE question_id IS NOT NULL;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0009_add_better_indexes"),
    ]

    operations = [migrations.RunSQL(INDEX_SQL)]
