# Generated by Django 3.2.6 on 2021-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0013_alter_pollwordcloud_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactactivity",
            name="scheme",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
