# Generated by Django 3.2.6 on 2021-09-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0015_schemesegment"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollstats",
            name="scheme_segment",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="stats.schemesegment"),
        ),
    ]
