# Generated by Django 3.2.6 on 2021-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0018_better_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactactivity",
            name="used",
            field=models.BooleanField(null=True),
        ),
    ]
