# Generated by Django 3.2.8 on 2021-11-01 16:51

from django.db import migrations

# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_USED_SCHEME_NOT_NULL = """
DROP INDEX IF EXISTS stats_contactactivity_org_id_date_used_scheme__not_null;
"""


# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_USED_GENDER_NOT_NULL = """
DROP INDEX IF EXISTS stats_contactactivity_org_id_date_used_gender_not_null;
"""

# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_USED_STATE_NOT_NULL = """
DROP INDEX IF EXISTS stats_contactactivity_org_id_date_used_state_not_null;
"""

# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_USED = """
DROP INDEX IF EXISTS stats_contactactivity_org_id_date_used;
"""


# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_GENDER_NOT_NULL = """
DROP INDEX IF EXISTS stats_contactactivity_org_id_date_gender_not_null;
"""

# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_STATE_NOT_NULL = """
DROP INDEX IF EXISTS stats_contactactivity_org_id_date_state_not_null;
"""

# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_SCHEME_NOT_NULL = """
DROP INDEX IF EXISTS stats_contactactivity_org_id_date_scheme_not_null;
"""

# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_GENDER = """
DROP INDEX IF EXISTS stats_contactactivity_org_id_date_gender;
"""

# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_DATE_STATE = """
DROP INDEX IF EXISTS stats_contactactivity_org_id_date_state;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0022_better_indexes"),
    ]

    operations = [
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_USED_SCHEME_NOT_NULL, ""),
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_USED_GENDER_NOT_NULL, ""),
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_USED_STATE_NOT_NULL, ""),
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_USED, ""),
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_GENDER_NOT_NULL, ""),
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_STATE_NOT_NULL, ""),
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_SCHEME_NOT_NULL, ""),
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_GENDER, ""),
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_DATE_STATE, ""),
    ]
