# Generated by Django 3.2.8 on 2021-11-04 11:05

from django.db import migrations

# language=SQL
INDEX_SQL_CONTACTACTIVITY_ORG_AGE_DATE_USED_NOT_NULL = """
CREATE INDEX IF NOT EXISTS stats_contactactivity_org_id_age_date_not_null_used on stats_contactactivity (org_id, date, (EXTRACT('year' FROM "stats_contactactivity"."date") - "stats_contactactivity"."born"), used) WHERE date IS NOT NULL and born IS NOT NULL and used;
"""

# language=SQL
INDEX_SQL_POLLSTATS_ORG_RESULT_CATEGORY_NOT_NULL = """
CREATE INDEX IF NOT EXISTS stats_pollstats_org_result_cat_not_null on stats_pollstats (org_id, flow_result_id, flow_result_category_id) WHERE flow_result_id IS NOT NULL AND flow_result_category_id IS NOT NULL;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0024_update_indexes_properly"),
    ]

    operations = [
        migrations.RunSQL(INDEX_SQL_CONTACTACTIVITY_ORG_AGE_DATE_USED_NOT_NULL, ""),
        migrations.RunSQL(INDEX_SQL_POLLSTATS_ORG_RESULT_CATEGORY_NOT_NULL, ""),
    ]
