# Generated by Django 3.2.8 on 2021-12-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0029_auto_20211025_1504"),
        ("flows", "0001_initial"),
        ("locations", "0006_boundary_backend"),
        ("stats", "0026_populate_flow_result_word_clouds"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollContactResult",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact", models.CharField(max_length=36)),
                ("flow", models.CharField(max_length=36)),
                ("text", models.TextField(null=True)),
                ("date", models.DateTimeField(null=True)),
                (
                    "age_segment",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="stats.agesegment"),
                ),
                (
                    "flow_result",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="flows.flowresult"),
                ),
                (
                    "flow_result_category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="flows.flowresultcategory"
                    ),
                ),
                (
                    "gender_segment",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="stats.gendersegment"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="locations.boundary"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="poll_contact_results",
                        to="orgs.org",
                    ),
                ),
                (
                    "scheme_segment",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="stats.schemesegment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactEngagementActivity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact", models.CharField(max_length=36)),
                ("date", models.DateField(help_text="The starting date for for the month")),
                ("used", models.BooleanField(null=True)),
                (
                    "age_segment",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="stats.agesegment"),
                ),
                (
                    "gender_segment",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="stats.gendersegment"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="locations.boundary"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_engagement_activities",
                        to="orgs.org",
                    ),
                ),
                (
                    "scheme_segment",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="stats.schemesegment"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pollcontactresult",
            index=models.Index(fields=["contact"], name="stats_pcr_contact"),
        ),
        migrations.AddIndex(
            model_name="pollcontactresult",
            index=models.Index(fields=["org", "flow", "contact"], name="stats_pcr_org_flow_contact"),
        ),
        migrations.AddIndex(
            model_name="pollcontactresult",
            index=models.Index(fields=["org", "flow"], name="stats_pcr_org_flow"),
        ),
        migrations.AddIndex(
            model_name="pollcontactresult",
            index=models.Index(fields=["org", "flow", "flow_result", "text"], name="stats_pcr_org_flow_result_text"),
        ),
        migrations.AddIndex(
            model_name="contactengagementactivity",
            index=models.Index(fields=["org", "contact"], name="stats_cea_org_contact"),
        ),
        migrations.AddIndex(
            model_name="contactengagementactivity",
            index=models.Index(fields=["org", "date"], name="stats_cea_org_date"),
        ),
        migrations.AddIndex(
            model_name="contactengagementactivity",
            index=models.Index(
                condition=models.Q(("used", True)), fields=["org", "date", "used"], name="stats_cea_org_date_used"
            ),
        ),
        migrations.AddIndex(
            model_name="contactengagementactivity",
            index=models.Index(
                condition=models.Q(("location__isnull", False), ("used", True)),
                fields=["org", "date", "location", "used"],
                name="stats_cea_org_date_state_used",
            ),
        ),
        migrations.AddIndex(
            model_name="contactengagementactivity",
            index=models.Index(
                condition=models.Q(("age_segment__isnull", False), ("used", True)),
                fields=["org", "date", "age_segment", "used"],
                name="stats_cea_org_date_age_used",
            ),
        ),
        migrations.AddIndex(
            model_name="contactengagementactivity",
            index=models.Index(
                condition=models.Q(("scheme_segment__isnull", False), ("used", True)),
                fields=["org", "date", "scheme_segment", "used"],
                name="stats_cea_org_date_scheme_used",
            ),
        ),
        migrations.AddIndex(
            model_name="contactengagementactivity",
            index=models.Index(
                condition=models.Q(("gender_segment__isnull", False), ("used", True)),
                fields=["org", "date", "gender_segment", "used"],
                name="stats_cea_org_date_gender_used",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contactengagementactivity",
            unique_together={("org", "contact", "date")},
        ),
    ]
