# Generated by Django 4.1.7 on 2023-04-13 13:59

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0027_contactactivitycounter_and_more"),
    ]

    operations = [InstallSQL("stats_0028")]
