# Generated by Django 3.2.8 on 2021-12-02 14:23

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0027_auto_20211202_1422"),
    ]

    operations = [InstallSQL("stats_0028")]
