# Generated by Django 5.0.8 on 2024-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0033_rename_orgs_orgbac_org_id_607508_idx_orgs_orgbac_org_slug_idx_and_more"),
        ("stats", "0028_activities_counter_triggers"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contactactivity",
            new_name="stats_ct_actvt_org_contact_idx",
            old_fields=("org", "contact"),
        ),
        migrations.RenameIndex(
            model_name="contactactivity",
            new_name="stats_ct_actvt_org_date_idx",
            old_fields=("org", "date"),
        ),
        migrations.AlterUniqueTogether(
            name="contactactivity",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="contactactivity",
            constraint=models.UniqueConstraint(
                fields=("org", "contact", "date"), name="stats_contactactivity_org_id_contact_date_348227aa_uniq"
            ),
        ),
    ]
