# Generated by Django 5.1 on 2024-08-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0029_rename_contactactivity_org_contact_stats_ct_actvt_org_contact_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contactactivity",
            name="stats_contactactivity_org_id_contact_dec2fa2d_idx",
        ),
        migrations.RemoveIndex(
            model_name="contactactivity",
            name="stats_contactactivity_org_id_date_fff018fc_idx",
        ),
    ]
