# Generated by Django 5.2.8 on 2025-11-24 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0002_alter_flowresult_unique_together_and_more"),
        ("orgs", "0033_rename_orgs_orgbac_org_id_607508_idx_orgs_orgbac_org_slug_idx_and_more"),
        ("stats", "0030_remove_contactactivity_stats_contactactivity_org_id_contact_dec2fa2d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollEngagementDailyCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("count", models.BigIntegerField(default=0)),
                ("is_squashed", models.BooleanField(default=False)),
                ("scope", models.CharField(max_length=128)),
                ("day", models.DateField()),
                (
                    "is_responded",
                    models.BooleanField(
                        help_text="Whether the contact responded to the poll or only received it", null=True
                    ),
                ),
                ("flow_result", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="flows.flowresult")),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="poll_engagement_stats",
                        to="orgs.org",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["org", "flow_result"], name="stats_pedc_org_flowresult_idx"),
                    models.Index(fields=["org", "day"], name="stats_pedc_org_date_idx"),
                    models.Index(
                        condition=models.Q(("is_squashed", False)),
                        fields=["org", "flow_result", "is_responded", "scope", "day"],
                        name="stats_pedc_unsquashed",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PollStatsCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("count", models.BigIntegerField(default=0)),
                ("is_squashed", models.BooleanField(default=False)),
                ("scope", models.CharField(max_length=128)),
                ("flow_result", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="flows.flowresult")),
                (
                    "flow_result_category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="flows.flowresultcategory"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="poll_stats_segments", to="orgs.org"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["org", "flow_result"], name="stats_psc_org_flowresult_idx"),
                    models.Index(
                        condition=models.Q(("is_squashed", False)),
                        fields=["org", "flow_result", "flow_result_category", "scope"],
                        name="stats_psc_unsquashed",
                    ),
                ],
            },
        ),
    ]
