# Generated by Django 5.2.7 on 2025-11-18 15:47

from django.db import migrations


def noop(apps, schema_editor):  # pragma: no cover
    pass


def migrate_poll_stats(apps, schema_editor):  # pragma: no cover
    PollStats = apps.get_model("stats", "PollStats")

    stats = PollStats.objects.all().order_by("id").iterator(chunk_size=1000)
    for stat in stats:

        new_records = []
        update_fields = []
        if stat.age_segment_id is not None:
            new_records.append(
                PollStats(
                    org=stat.org,
                    question_id=stat.question_id,
                    flow_result_id=stat.flow_result_id,
                    category_id=stat.category_id,
                    flow_result_category_id=stat.flow_result_category_id,
                    age_segment_id=stat.age_segment_id,
                    date=stat.date,
                    count=stat.count,
                    is_squashed=False,
                )
            )
            stat.age_segment_id = None
            update_fields.append("age_segment_id")

        if stat.gender_segment_id is not None:
            new_records.append(
                PollStats(
                    org=stat.org,
                    question_id=stat.question_id,
                    flow_result_id=stat.flow_result_id,
                    category_id=stat.category_id,
                    flow_result_category_id=stat.flow_result_category_id,
                    gender_segment_id=stat.gender_segment_id,
                    date=stat.date,
                    count=stat.count,
                    is_squashed=False,
                )
            )
            stat.gender_segment_id = None
            update_fields.append("gender_segment_id")

        if stat.scheme_segment_id is not None:
            new_records.append(
                PollStats(
                    org=stat.org,
                    question_id=stat.question_id,
                    flow_result_id=stat.flow_result_id,
                    category_id=stat.category_id,
                    flow_result_category_id=stat.flow_result_category_id,
                    scheme_segment_id=stat.scheme_segment_id,
                    date=stat.date,
                    count=stat.count,
                    is_squashed=False,
                )
            )
            stat.scheme_segment_id = None
            update_fields.append("scheme_segment_id")

        if stat.location_id is not None:
            new_records.append(
                PollStats(
                    org=stat.org,
                    question_id=stat.question_id,
                    flow_result_id=stat.flow_result_id,
                    category_id=stat.category_id,
                    flow_result_category_id=stat.flow_result_category_id,
                    location_id=stat.location_id,
                    date=stat.date,
                    count=stat.count,
                    is_squashed=False,
                )
            )
            stat.location_id = None
            update_fields.append("location_id")

        if new_records:
            PollStats.objects.bulk_create(new_records)

        stat.is_squashed = False
        update_fields.append("is_squashed")
        stat.save(update_fields=update_fields)


def apply_manual():  # pragma: no cover
    from django.apps import apps

    migrate_poll_stats(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0030_remove_contactactivity_stats_contactactivity_org_id_contact_dec2fa2d_idx_and_more"),
    ]

    operations = [migrations.RunPython(migrate_poll_stats, noop)]
