# Generated by Django 5.2.8 on 2025-11-18 15:47

import time

from django.db import migrations, transaction

from django.core.cache import cache

from ureport.utils import chunk_list


def noop(apps, schema_editor):  # pragma: no cover
    pass


def migrate_poll_stats(apps, schema_editor):  # pragma: no cover
    """
    Migrates PollStats records to ensure each record has at most one segment type.
    Records with multiple segments are split into separate records, one per segment type.
    """
    PollStats = apps.get_model("stats", "PollStats")
    last_migrated_poll_stats_id_key = "migrated_poll_stats_last_id"
    last_id = cache.get(last_migrated_poll_stats_id_key, 0)

    all_stats_ids = PollStats.objects.all().filter(id__gte=last_id).exclude(age_segment_id=None, gender_segment_id=None, scheme_segment_id=None, location_id=None, is_squashed=False).order_by("id").values_list("id", flat=True)
    total = all_stats_ids.count()
    print(f"Total PollStats to migrate: {total}")
    start_time = time.time()

    processed = 0
    for batch in chunk_list(all_stats_ids, 1000):
        batch_ids = list(batch)
        stats = PollStats.objects.filter(id__in=batch_ids)
        segment_fields = [
            "age_segment_id",
            "gender_segment_id",
            "scheme_segment_id",
            "location_id",
        ]

        with transaction.atomic():
            stats_to_update = []
            new_records = []
            for stat in stats:
                for field_name in segment_fields:
                    field_value = getattr(stat, field_name)
                    if field_value is not None:
                        kwargs = {
                            "org": stat.org,
                            "question_id": stat.question_id,
                            "flow_result_id": stat.flow_result_id,
                            "category_id": stat.category_id,
                            "flow_result_category_id": stat.flow_result_category_id,
                            "date": stat.date,
                            "count": stat.count,
                            "is_squashed": False,
                            field_name: field_value,
                        }
                        new_records.append(PollStats(**kwargs))
                        setattr(stat, field_name, None)

                stat.is_squashed = False
                stats_to_update.append(stat)

            if new_records:
                PollStats.objects.bulk_create(new_records, batch_size=1000)
            if stats_to_update:
                PollStats.objects.bulk_update(stats_to_update, ["age_segment_id", "gender_segment_id", "scheme_segment_id", "location_id", "is_squashed"], batch_size=1000)

        cache.set(last_migrated_poll_stats_id_key, batch_ids[-1], None)

        processed += len(batch_ids)
        elapsed = time.time() - start_time
        print(f"Migrated {processed} of {total} PollStats in {elapsed:.1f} seconds")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    migrate_poll_stats(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0030_remove_contactactivity_stats_contactactivity_org_id_contact_dec2fa2d_idx_and_more"),
    ]

    operations = [migrations.RunPython(migrate_poll_stats, noop)]
