# Generated by Django 5.2.8 on 2025-11-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0002_alter_flowresult_unique_together_and_more"),
        ("orgs", "0033_rename_orgs_orgbac_org_id_607508_idx_orgs_orgbac_org_slug_idx_and_more"),
        ("stats", "0030_remove_contactactivity_stats_contactactivity_org_id_contact_dec2fa2d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollEngagementStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_responded",
                    models.BooleanField(help_text="Whether the poll got responded to or just sent", null=True),
                ),
                ("scope", models.CharField(help_text="The scope of this engagement stat", max_length=64)),
                ("date", models.DateField(help_text="The date for the engagement stats")),
                ("count", models.IntegerField(default=0, help_text="Number of items with this counter")),
                ("is_squashed", models.BooleanField(help_text="Whether this row was created by squashing", null=True)),
                ("flow_result", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="flows.flowresult")),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="poll_engagement_stats",
                        to="orgs.org",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["org", "flow_result"], name="pestats_org_flowresult_idx"),
                    models.Index(fields=["org", "date"], name="pestats_org_date_idx"),
                    models.Index(
                        condition=models.Q(("is_squashed", False)),
                        fields=["org", "flow_result", "is_responded", "date", "scope"],
                        name="pollengagementstats_unsquashed",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PollStatsSegment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(help_text="The scope of this segment", max_length=64)),
                ("count", models.IntegerField(default=0, help_text="Number of items with this counter")),
                ("is_squashed", models.BooleanField(help_text="Whether this row was created by squashing", null=True)),
                ("flow_result", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="flows.flowresult")),
                (
                    "flow_result_category",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="flows.flowresultcategory"
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="poll_stats_segments", to="orgs.org"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["org", "flow_result"], name="ps_sgmnts_org_flowresult_idx"),
                    models.Index(
                        condition=models.Q(("is_squashed", False)),
                        fields=["org", "flow_result", "flow_result_category", "scope"],
                        name="pollstatssegment_unsquashed",
                    ),
                ],
            },
        ),
    ]
