# Generated by Django 5.2.8 on 2025-11-20 12:35

from django.db import migrations


# language=SQL
CONSTRAINT_SQL_POLLSTATS_ONE_SEGMENT_SET_MAX = """
ALTER TABLE stats_pollstats ADD CONSTRAINT check_pollstats_only_one_segment_set CHECK (num_nonnulls(age_segment_id, gender_segment_id, location_id, scheme_segment_id) <= 1);
"""

# language=SQL
CONSTRAINT_SQL_POLLSTATS_ONE_SEGMENT_SET_MAX_DROP = """
ALTER TABLE stats_pollstats DROP CONSTRAINT IF EXISTS check_pollstats_only_one_segment_set;
"""

class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0031_migrate_poll_stats"),
    ]

    operations = [
        migrations.RunSQL(CONSTRAINT_SQL_POLLSTATS_ONE_SEGMENT_SET_MAX, CONSTRAINT_SQL_POLLSTATS_ONE_SEGMENT_SET_MAX_DROP),
    ]
