# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_auto_20180316_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresult',
            name='backend',
            field=models.CharField(default='rapidpro', max_length=16),
        ),
    ]
