# Generated by Django 2.1.5 on 2019-06-18 13:19

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [("polls", "0053_poll_backend")]

    operations = [InstallSQL("polls_0054")]
