# Generated by Django 2.2.3 on 2019-08-14 07:55

from django.db import migrations

# language=SQL
INDEX_SQL = """
CREATE INDEX polls_pollquestion_ruleset_uuid
ON polls_pollquestion (ruleset_uuid);
"""


class Migration(migrations.Migration):
    dependencies = [("polls", "0053_poll_backend")]

    operations = [migrations.RunSQL(INDEX_SQL)]
