# Generated by Django 2.2.3 on 2019-08-20 09:41

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):
    dependencies = [("polls", "0054_add_index_poll_question_ruleset_uuid"), ("stats", "0003_contactactivity")]

    operations = [InstallSQL("polls_0055")]
