# Generated by Django 2.2.5 on 2019-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("polls", "0055_install_triggers")]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="response_author",
            field=models.CharField(
                blank=True, help_text="The writer of the response story", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="response_content",
            field=models.TextField(blank=True, help_text="The body of text for the story", null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="response_title",
            field=models.CharField(
                blank=True, help_text="The title for this response story", max_length=255, null=True
            ),
        ),
    ]
