# Generated by Django 2.2.9 on 2020-02-06 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0057_poll_stopped_syncing"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PollResultsCounter",
        ),
    ]
