# Generated by Django 2.2.10 on 2020-05-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0058_delete_pollresultscounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollresponsecategory",
            name="category_displayed",
            field=models.TextField(null=True),
        ),
    ]
