# Generated by Django 2.2.20 on 2021-07-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0001_initial"),
        ("polls", "0060_populate_category_displayed"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollquestion",
            name="flow_result",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="flows.FlowResult"),
        ),
        migrations.AddField(
            model_name="pollresponsecategory",
            name="flow_result_category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="flows.FlowResultCategory"
            ),
        ),
    ]
