# Generated by Django 2.2.20 on 2021-07-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0001_initial"),
        ("polls", "0062_populate_flow_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollquestion",
            name="flow_result",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="flows.FlowResult"),
        ),
        migrations.AlterField(
            model_name="pollresponsecategory",
            name="flow_result_category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="flows.FlowResultCategory"),
        ),
        migrations.AddConstraint(
            model_name="pollquestion",
            constraint=models.UniqueConstraint(
                fields=["poll", "flow_result"], name="polls_pollquestion_poll_id_flow_result_id_608a2446_uniq"
            ),
        ),
    ]
