# Generated by Django 2.2.20 on 2021-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0001_initial"),
        ("polls", "0064_deduplicate_pollresponsecategories"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pollresponsecategory",
            constraint=models.UniqueConstraint(
                fields=["question", "flow_result_category"],
                name="polls_pollresponsecatego_question_id_flow_result__4db1cb7e_uniq",
            ),
        ),
    ]
