# Generated by Django 3.2.6 on 2021-08-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0001_initial"),
        ("polls", "0065_auto_20210728_1326"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="topics",
            field=models.ManyToManyField(to="topics.Topic"),
        ),
    ]
