# Generated by Django 3.2.6 on 2021-08-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("polls", "0065_auto_20210728_1326"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tags.Tag"),
        ),
    ]
