# Generated by Django 3.2.6 on 2021-09-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0066_poll_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollresult",
            name="scheme",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
