# Generated by Django 3.2.6 on 2021-10-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0068_install_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollquestion",
            name="color_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "-----"),
                    ("D1", "Dark 1 background and White text"),
                    ("L1", "Light 1 background and Black text"),
                    ("D2", "Dark 2 background and White text"),
                    ("D3", "Dark 3 background and Black text"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
