# Generated by Django 3.2.6 on 2021-10-19 09:14

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0069_pollquestion_color_choice"),
    ]

    operations = [InstallSQL("polls_0070")]
