# Generated by Django 4.1.7 on 2023-03-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0001_initial"),
        ("polls", "0072_alter_featuredresponse_created_by_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pollquestion",
            index=models.Index(
                fields=["poll", "is_active", "flow_result"],
                name="polls_pollquestion_poll_id_is_active_flow_r_deda78e0_idx",
            ),
        ),
    ]
