# Generated by Django 4.1.7 on 2023-03-29 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0001_initial"),
        ("polls", "0072_alter_featuredresponse_created_by_and_more"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="poll",
            index_together={("org", "is_active", "id")},
        ),
        migrations.AlterIndexTogether(
            name="pollquestion",
            index_together={("poll", "is_active", "flow_result")},
        ),
    ]
