# Generated by Django 4.2.6 on 2023-10-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0073_alter_poll_index_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="published",
            field=models.BooleanField(
                default=True, help_text="Whether this poll should be visible/hidden on the public site"
            ),
        ),
    ]
