# Generated by Django 4.2.6 on 2023-10-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0031_alter_orgbackend_index_together"),
        ("polls", "0075_populate_published"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["org", "published", "id"], name="polls_poll_org_id_published_id_6b0e6423_idx"),
        ),
    ]
