# Generated by Django 4.2.6 on 2023-10-25 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0031_alter_orgbackend_index_together"),
        ("polls", "0075_populate_published"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="poll",
            index_together={("org", "published", "id")},
        ),
    ]
