# Generated by Django 5.0.8 on 2024-08-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0076_alter_poll_index_together"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="poll",
            new_name="polls_poll_org_id_3461d6_idx",
            old_fields=("org", "published", "id"),
        ),
        migrations.RenameIndex(
            model_name="pollquestion",
            new_name="polls_pollq_poll_id_68485b_idx",
            old_fields=("poll", "is_active", "flow_result"),
        ),
        migrations.RenameIndex(
            model_name="pollresult",
            new_name="polls_pollr_org_id_428d8a_idx",
            old_fields=("org", "flow", "ruleset", "text"),
        ),
        migrations.RenameIndex(
            model_name="pollresult",
            new_name="polls_pollr_org_id_0f793f_idx",
            old_fields=("org", "flow"),
        ),
    ]
