# Generated by Django 5.1 on 2024-08-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0077_rename_poll_org_published_id_polls_poll_org_pblshd_id_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="poll",
            name="polls_poll_org_id_published_id_6b0e6423_idx",
        ),
        migrations.RemoveIndex(
            model_name="pollquestion",
            name="polls_pollquestion_poll_id_is_active_flow_r_deda78e0_idx",
        ),
        migrations.RemoveIndex(
            model_name="pollresult",
            name="polls_pollresult_org_id_dfd50a4d782b673_idx",
        ),
        migrations.RemoveIndex(
            model_name="pollresult",
            name="polls_pollresult_org_id_68705a7f5a6456ed_idx",
        ),
    ]
