# Generated by Django 5.1.2 on 2025-01-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0079_remove_poll_polls_poll_org_id_published_id_6b0e6423_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollresult",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
