# Generated by Django 5.2.7 on 2025-10-28 10:11

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0080_alter_pollresult_id"),
    ]

    operations = [InstallSQL("polls_0081")]
