# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 13:36
from __future__ import unicode_literals

import logging
import time

from django.db import migrations, models

from ureport.utils import chunk_list

logger = logging.getLogger(__name__)


def populate_contacts_backend(apps, schema_editor):
    Contact = apps.get_model("contacts", "Contact")
    ContactField = apps.get_model("contacts", "ContactField")
    Org = apps.get_model("orgs", "Org")

    start = time.time()

    for org in Org.objects.all():
        backend = org.backends.filter(slug="rapidpro").first()
        ContactField.objects.filter(org=org).update(backend=backend)
        logger.info("Processed fields")

        i = 0
        contact_ids = Contact.objects.filter(org_id=org.id).values_list("id", flat=True)

        for batch in chunk_list(contact_ids, 1000):
            updated = Contact.objects.filter(id__in=batch, org_id=org.id).update(backend_id=backend.id)
            i += updated
            logger.info("Processed %d / %d contacts in %ds" % (i, len(contact_ids), time.time() - start))

        logger.info("Finished setting contacts and fields backend for org %s" % org.name)


class Migration(migrations.Migration):
    dependencies = [("orgs", "0025_auto_20180322_1415"), ("contacts", "0017_auto_20180405_1330")]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="backend",
            field=models.ForeignKey(null=True, on_delete=models.PROTECT, to="orgs.OrgBackend"),
        ),
        migrations.AddField(
            model_name="contactfield",
            name="backend",
            field=models.ForeignKey(null=True, on_delete=models.PROTECT, to="orgs.OrgBackend"),
        ),
        migrations.RunPython(populate_contacts_backend),
    ]
