# Generated by Django 2.2.3 on 2019-08-27 16:39

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):
    dependencies = [("contacts", "0018_auto_20180405_1336")]

    operations = [InstallSQL("contacts_0019")]
