# Generated by Django 2.1.5 on 2019-06-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_fix_org_config_rapidpro'),
        ('contacts', '0018_auto_20180405_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=36)),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField(help_text='The starting date for for the month')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_activities', to='orgs.Org')),
            ],
        ),
    ]
