# Generated by Django 2.1.5 on 2019-06-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orgs", "0026_fix_org_config_rapidpro"), ("contacts", "0019_contactactivity")]

    operations = [migrations.AlterIndexTogether(name="contactactivity", index_together={("org", "contact")})]
