# Generated by Django 2.2.3 on 2019-09-09 22:18

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):
    dependencies = [("contacts", "0019_install_triggers")]

    operations = [InstallSQL("contacts_0020")]
