# Generated by Django 2.2.5 on 2019-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("contacts", "0020_install_triggers")]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                help_text="Gender of the contact",
                max_length=1,
                null=True,
                verbose_name="Gender",
            ),
        )
    ]
