# Generated by Django 2.2.5 on 2019-10-07 21:10

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):
    dependencies = [("contacts", "0021_auto_20190926_1554")]

    operations = [InstallSQL("contacts_0022")]
