# Generated by Django 2.2.13 on 2021-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0023_auto_20200602_0436"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reporterscounter",
            index=models.Index(fields=["org", "type", "count"], name="contacts_rptrscntr_org_typ_cnt"),
        ),
    ]
