# Generated by Django 3.2.6 on 2021-08-16 14:39

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0024_auto_20210126_1732"),
    ]

    operations = [InstallSQL("contacts_0025")]
