# Generated by Django 3.2.6 on 2021-09-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0025_install_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="scheme",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
