# Generated by Django 3.2.6 on 2021-09-07 09:54

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0026_contact_scheme"),
    ]

    operations = [InstallSQL("contacts_0027")]
