# Generated by Django 3.2.8 on 2021-11-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_install_triggers'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='reporterscounter',
            index_together=set(),
        ),
    ]
