# Generated by Django 5.0.8 on 2024-08-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0027_install_triggers"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reporterscounter",
            new_name="contacts_re_org_id_d53a00_idx",
            old_fields=("org", "type"),
        ),
    ]
