# Generated by Django 5.0.8 on 2024-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0027_install_triggers"),
        ("orgs", "0033_rename_orgs_orgbac_org_id_607508_idx_orgs_orgbac_org_slug_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reporterscounter",
            new_name="contacts_rptrscntr_org_id_idx",
            old_fields=("org", "type"),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("org", "uuid"), name="contacts_contact_org_id_563dcefdcba190b9_uniq"
            ),
        ),
    ]
