# Generated by Django 5.1 on 2024-08-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0028_rename_reporterscounter_org_type_contacts_rptrscntr_org_id_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="reporterscounter",
            name="contacts_reporterscounter_org_id_6e256be32b9ee5bf_idx",
        ),
    ]
