# Generated by Django 5.2.7 on 2025-11-18 08:33

from django.db import migrations

from ureport.sql import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0029_remove_reporterscounter_contacts_reporterscounter_org_id_6e256be32b9ee5bf_idx"),
    ]

    operations = [InstallSQL("contacts_0030")]
