# Generated by Django 6.0.6 on 2026-08-11 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "orgs",
            "0033_rename_orgs_orgbac_org_id_607508_idx_orgs_orgbac_org_slug_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(max_length=64)),
                ("scope", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("R", "Running"),
                            ("C", "Complete"),
                            ("F", "Failed"),
                            ("X", "Paused"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("cursor", models.JSONField(blank=True, default=dict)),
                ("lease_owner", models.CharField(max_length=255, null=True)),
                ("lease_expires_on", models.DateTimeField(null=True)),
                ("started_on", models.DateTimeField(null=True)),
                ("ended_on", models.DateTimeField(null=True)),
                ("progress", models.JSONField(blank=True, default=dict)),
                ("needs_finalize", models.BooleanField(default=False)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_jobs",
                        to="orgs.org",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["job_type", "status"], name="syncjobs_by_type_status"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "job_type", "scope"),
                        name="syncjobs_unique_job",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
