# Generated by Django 3.2.6 on 2021-10-06 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orgs", "0027_alter_org_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Whether this bot is featured and displayed on the homepage"
                    ),
                ),
                ("title", models.CharField(help_text="The title to display for this bot", max_length=128)),
                (
                    "channel",
                    models.CharField(
                        help_text="The shortcode, number or bot name of the channel for this bot", max_length=128
                    ),
                ),
                ("keyword", models.CharField(help_text="The keyword for this bot", max_length=128)),
                ("deeplink", models.URLField(help_text="The deeplink for this bot, if any is available", null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="The description text for this bot", max_length=640, null=True
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="The priority number for this bot among others on a list, high priority comes first",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bots_bot_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bots_bot_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="The organization this bot is part of",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bots",
                        to="orgs.org",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
