# Generated by Django 5.0.8 on 2024-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0001_initial"),
        ("orgs", "0033_rename_orgs_orgbac_org_id_607508_idx_orgs_orgbac_org_slug_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flowresult",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="flowresult",
            constraint=models.UniqueConstraint(
                fields=("org", "flow_uuid", "result_uuid"),
                name="flows_flowresult_org_id_flow_uuid_result_uuid_5efa8f2d_uniq",
            ),
        ),
    ]
