# Generated by Django 2.2.3 on 2019-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("assets", "0004_auto_20170615_1455")]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_type",
            field=models.CharField(
                choices=[("B", "Banner"), ("P", "Pattern"), ("F", "Flag"), ("L", "LOGO")],
                default="P",
                max_length=1,
                verbose_name="Image type",
            ),
        )
    ]
