# Generated by Django 3.2.8 on 2021-11-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_auto_20190828_1846"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="The priority number for this image among others on a list, high priority comes first",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_type",
            field=models.CharField(
                choices=[("B", "Banner"), ("P", "Pattern"), ("F", "Flag"), ("L", "Logo"), ("A", "About Partner Logo")],
                default="A",
                max_length=1,
                verbose_name="Image type",
            ),
        ),
    ]
