# Generated by Django 3.2.8 on 2021-10-27 19:00

import functools

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import dash.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orgs", "0029_auto_20211025_1504"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("title", models.CharField(help_text="The title to display for this landing page", max_length=128)),
                (
                    "slug",
                    models.CharField(help_text="The slug to use on the link for this landing page", max_length=128),
                ),
                ("content", models.TextField(help_text="The body of text for the landing page")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="The image file to use for the page",
                        null=True,
                        upload_to=functools.partial(dash.utils.generate_file_path, *("landingpages",), **{}),
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landingpages_landingpage_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landingpages_landingpage_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="The organization this landing page is part of",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landing_pages",
                        to="orgs.org",
                    ),
                ),
            ],
            options={
                "index_together": {("org", "slug")},
            },
        ),
        migrations.AddConstraint(
            model_name="landingpage",
            constraint=models.UniqueConstraint(
                fields=["org", "slug"], name="landingpages_landingpage_org_id_slug_f7f1304e_uniq"
            ),
        ),
    ]
