# Generated by Django 5.0.8 on 2024-08-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0004_alter_landingpage_created_by_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="landingpage",
            new_name="landingpage_org_id_80f356_idx",
            old_fields=("org", "slug"),
        ),
    ]
