# Generated by Django 4.1.7 on 2023-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_boundary_backend"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="boundary",
            index=models.Index(
                fields=["org", "level", "name", "osm_id"],
                name="locations_boundary_org_id_level_name_osm_id_daf5c9a8_idx",
            ),
        ),
    ]
