# Generated by Django 4.1.7 on 2023-03-29 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_boundary_backend"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="boundary",
            index_together={("org", "level", "name", "osm_id")},
        ),
    ]
