# Generated by Django 5.0.8 on 2024-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_alter_boundary_index_together"),
        ("orgs", "0033_rename_orgs_orgbac_org_id_607508_idx_orgs_orgbac_org_slug_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="boundary",
            new_name="locations_bd_org_lv_nm_osm_idx",
            old_fields=("org", "level", "name", "osm_id"),
        ),
        migrations.AlterUniqueTogether(
            name="boundary",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="boundary",
            constraint=models.UniqueConstraint(
                fields=("org", "osm_id"), name="locations_boundary_org_id_5c2d99160b82334a_uniq"
            ),
        ),
    ]
