# Generated by Django 5.0.8 on 2024-08-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_alter_boundary_index_together"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="boundary",
            new_name="locations_b_org_id_ee9365_idx",
            old_fields=("org", "level", "name", "osm_id"),
        ),
    ]
