# Generated by Django 5.1 on 2024-08-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_rename_boundary_org_level_name_osm_id_locations_bd_org_lv_nm_osm_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="boundary",
            name="locations_boundary_org_id_level_name_osm_id_daf5c9a8_idx",
        ),
    ]
